user-api:
  build: .
  command: java -jar /user-api/app.jar
  container_name: user-api
  links:
    - db:user.database
  environment:
    - DATABASE_URL=jdbc:postgresql://user.database/user_api?user=user_api&password=pwd

dev:
  build: .
  command: lein run rollback && lein run migrate && lein run
  container_name: user-dev
  links:
    - db:user.database
  environment:
    - DATABASE_URL=jdbc:postgresql://user.database/user_api?user=user_api&password=pwd
  
db:
  image: postgres
  expose:
    - "5432"
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=user_api
    - POSTGRES_PASSWORD=pwd
    - POSTGRES_DB=user_api

